# Server
server.port=${PORT:8080}
spring.application.name=doctor-appointment-system

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/doctor_appointment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# JWT
jwt.secret=${JWT_SECRET:z2aWN5PNVHuFJmI1qrD8WNGwQhDqQEkTCy7ZB9f6eAQ=}
jwt.expiration=86400000